FROM ghcr.io/mrs-electronics-inc/qt-docker/base:latest

# Add image metadata.
LABEL org.opencontainers.image.source="https://github.com/mrs-electronics-inc/qt-docker"
LABEL org.opencontainers.image.description="Docker image containing MRS Qt toolchains for NeuralPlex projects"
LABEL org.opencontainers.image.licenses="MIT"
